// const seasons = [
//   [
//     {
//       title: 'Pilot',
//       hints: [
//         'Corporate memos go in a special filing cabinet'
//       ]
//     },
//   ],
//   [
//     {
//       title: 'The Dundies',
//       hints: [
//         'Corporate memos go in a special filing cabinet'
//       ]
//     },
//   ],
//   [
//     {
//       title: 'Gay Witch Hunt',
//       hints: [
//         'Corporate memos go in a special filing cabinet'
//       ]
//     },
//   ]
// ]

// let episodeCount = 0;
// let seenHints = [];

// const episodes = seasons.map((listOfEpisodes, seasonIndex) => {
//   const seasonNumber = seasonIndex + 1;

//   return listOfEpisodes.map((episode, episodeIndex => {
//     episodeCount++;
//     const seasonEpisodeNum = episodeIndex + 1;
//     const totalEpisodeNum = episodeCount;
//     const episodeId = `${seasonNumber}:${seasonEpisodeNum}:${totalEpisodeNum}`;
//     return { ...episode, seasonNumber, seasonEpisodeNum, totalEpisodeNum, episodeId };
//   });
// }).flat()


const answers = [
  {
    "Episode Number Overall": 1,
    "Season Number": 1,
    "Episode": 1,
    "Title": "Pilot",
    "Hint":"Corporate memos go in a special filing cabinet",
  },
  {
    "Episode Number Overall": 2,
    "Season Number": 1,
    "Episode": 2,
    "Title": "Diversity Day",
    "Hint":"That's not an appropriate Chris Tucker impression...",
  },
  {
    "Episode Number Overall": 3,
    "Season Number": 1,
    "Episode": 3,
    "Title": "Healthcare",
    "Hint":"A uterus is different from a vagina. I still have a vagina.",
  },
  {
    "Episode Number Overall": 4,
    "Season Number": 1,
    "Episode": 4,
    "Title": "The Alliance",
    "Hint":"Dwight and Jim should not work together...",
  },
  {
    "Episode Number Overall": 5,
    "Season Number": 1,
    "Episode": 5,
    "Title": "Basketball",
    "Hint":"Kevin really hit every shot!",
  },
  {
    "Episode Number Overall": 6,
    "Season Number": 1,
    "Episode": 6,
    "Title": "Hot Girl",
    "Hint":"Dwight ROCKS that purse!",
  },
  {
    "Episode Number Overall": 7,
    "Season Number": 2,
    "Episode": 1,
    "Title": "The Dundies",
    "Hint":"I feel God in this Chilis tonight.",
  },
  {
    "Episode Number Overall": 8,
    "Season Number": 2,
    "Episode": 2,
    "Title": "Sexual Harassment",
    "Hint":"Let's just treat every day like Pam's Mom is coming.",
  },
  {
    "Episode Number Overall": 9,
    "Season Number": 2,
    "Episode": 3,
    "Title": "Office Olympics",
    "Hint":"Flonkerton : Box of Paper Snow Shoe Racing",
  },
  {
    "Episode Number Overall": 10,
    "Season Number": 2,
    "Episode": 4,
    "Title": "The Fire",
    "Hint":"Mmm, cheese pita",
  },
  {
    "Episode Number Overall": 11,
    "Season Number": 2,
    "Episode": 5,
    "Title": "Halloween",
    "Hint":"Sorry, Devon",
  },
  {
    "Episode Number Overall": 12,
    "Season Number": 2,
    "Episode": 6,
    "Title": "The Fight",
    "Hint":"Two punches : Me punching you and you hitting the floor",
  },
  {
    "Episode Number Overall": 13,
    "Season Number": 2,
    "Episode": 7,
    "Title": "The Client",
    "Hint":"I want my baby back baby back baby back",
  },
  {
    "Episode Number Overall": 14,
    "Season Number": 2,
    "Episode": 8,
    "Title": "Performance Review",
    "Hint":"'I guess I missed you' What do you think she meant by that?",
  },
  {
    "Episode Number Overall": 15,
    "Season Number": 2,
    "Episode": 9,
    "Title": "Email Surveillance",
    "Hint":"People hear the term “big brother”, they immediately think it’s scary or bad, but I don’t. I think, wow, I love my big brother. ",
  },
  {
    "Episode Number Overall": 16,
    "Season Number": 2,
    "Episode": 10,
    "Title": "Christmas Party",
    "Hint":"Look at how old that old iPod is.",
  },
  {
    "Episode Number Overall": 17,
    "Season Number": 2,
    "Episode": 11,
    "Title": "Booze Cruise",
    "Hint":"Rob Riggle is an American Treasure",
  },
  {
    "Episode Number Overall": 18,
    "Season Number": 2,
    "Episode": 12,
    "Title": "The Injury",
    "Hint":"You burnt... your foot... on a Foreman grill...",
  },
  {
    "Episode Number Overall": 19,
    "Season Number": 2,
    "Episode": 13,
    "Title": "The Secret",
    "Hint":"Michael spills the beans to Beasley.",
  },
  {
    "Episode Number Overall": 20,
    "Season Number": 2,
    "Episode": 14,
    "Title": "The Carpet",
    "Hint":"Hey guys. Somebody making soup?",
  },
  {
    "Episode Number Overall": 21,
    "Season Number": 2,
    "Episode": 15,
    "Title": "Boys and Girls",
    "Hint":"Do black people like pizza?",
  },
  {
    "Episode Number Overall": 22,
    "Season Number": 2,
    "Episode": 16,
    "Title": "Valentine’s Day",
    "Hint":"Are we surprised Roy let her down while Bob Vance overperformed?",
  },
  {
    "Episode Number Overall": 23,
    "Season Number": 2,
    "Episode": 17,
    "Title": "Dwight’s Speech",
    "Hint":"IT IS A PRIVELIGE TO FIGHT!",
  },
  {
    "Episode Number Overall": 24,
    "Season Number": 2,
    "Episode": 18,
    "Title": "Take Your Daughter to Work Day",
    "Hint":"Okay Mr. Poop!",
  },
  {
    "Episode Number Overall": 25,
    "Season Number": 2,
    "Episode": 19,
    "Title": "Michael’s Birthday",
    "Hint":"So I have the perfect icebreaker if I ever meet Teri Hatcher.",
  },
  {
    "Episode Number Overall": 26,
    "Season Number": 2,
    "Episode": 20,
    "Title": "Drug Testing",
    "Hint":"That is Northern Lights Cannabis Indica.",
  },
  {
    "Episode Number Overall": 27,
    "Season Number": 2,
    "Episode": 21,
    "Title": "Conflict Resolution",
    "Hint":"This is so much more offensive to me than hardcore porno.",
  },
  {
    "Episode Number Overall": 28,
    "Season Number": 2,
    "Episode": 22,
    "Title": "Casino Night",
    "Hint":"Guys, the Afghanistananies.",
  },
  {
    "Episode Number Overall": 29,
    "Season Number": 3,
    "Episode": 1,
    "Title": "Gay Witch Hunt",
    "Hint":"I need to know who put my calculator in Jell-o, or I’m gonna lose MY FRICKIN’ MIND! ",
  },
  {
    "Episode Number Overall": 30,
    "Season Number": 3,
    "Episode": 2,
    "Title": "The Convention",
    "Hint":"A booze-fueled sex romp where anything goes",
  },
  {
    "Episode Number Overall": 31,
    "Season Number": 3,
    "Episode": 3,
    "Title": "The Coup",
    "Hint":"Your dentists name is Crentist? Sounds an awful lot like dentist...",
  },
  {
    "Episode Number Overall": 32,
    "Season Number": 3,
    "Episode": 4,
    "Title": "Grief Counseling",
    "Hint":"His capa was detated from his body",
  },
  {
    "Episode Number Overall": 33,
    "Season Number": 3,
    "Episode": 5,
    "Title": "Initiation",
    "Hint":"Is that your cousin Mose?",
  },
  {
    "Episode Number Overall": 34,
    "Season Number": 3,
    "Episode": 6,
    "Title": "Diwali",
    "Hint":"These s'mores are disgusting",
  },
  {
    "Episode Number Overall": 35,
    "Season Number": 3,
    "Episode": 7,
    "Title": "Branch Closing",
    "Hint":"You leveraged your new position with us into another offer?",
  },
  {
    "Episode Number Overall": 36,
    "Season Number": 3,
    "Episode": 8,
    "Title": "The Merger",
    "Hint":"...I would fire Anthony Gardner... ",
  },
  {
    "Episode Number Overall": 37,
    "Season Number": 3,
    "Episode": 9,
    "Title": "The Convict",
    "Hint":"The worst thing about prison? Was the... Dementors",
  },
  {
    "Episode Number Overall": 38,
    "Season Number": 3,
    "Episode": 10,
    "Title": "A Benihana Christmas",
    "Hint":"I was with you in a sense. I was in your heart... And next to your kids. What?",
  },
  {
    "Episode Number Overall": 39,
    "Season Number": 3,
    "Episode": 11,
    "Title": "A Benihana Christmas Part 2",
    "Hint":"(John Mayer got a Dundie for this episode)",
  },
  {
    "Episode Number Overall": 40,
    "Season Number": 3,
    "Episode": 12,
    "Title": "Back From Vacation",
    "Hint":"Sex. We had sex. I had sex with her. I had sex with Jan.",
  },
  {
    "Episode Number Overall": 41,
    "Season Number": 3,
    "Episode": 13,
    "Title": "Traveling Salesman",
    "Hint":"You can pay me back later for the makeover.",
  },
  {
    "Episode Number Overall": 42,
    "Season Number": 3,
    "Episode": 14,
    "Title": "The Return",
    "Hint":"Twiddly-diddly deet. Twiddly-diddly deet.",
  },
  {
    "Episode Number Overall": 43,
    "Season Number": 3,
    "Episode": 15,
    "Title": "Ben Franklin",
    "Hint":"I would say you are probably one of the sexiest presidents ever.",
  },
  {
    "Episode Number Overall": 44,
    "Season Number": 3,
    "Episode": 16,
    "Title": "Phyllis’ Wedding",
    "Hint":"I thought they only played The Police",
  },
  {
    "Episode Number Overall": 45,
    "Season Number": 3,
    "Episode": 17,
    "Title": "Business School",
    "Hint":"May your hats fly as high as your dreams",
  },
  {
    "Episode Number Overall": 46,
    "Season Number": 3,
    "Episode": 18,
    "Title": "Cocktails",
    "Hint":"Jim shoots hoops with David Wallace",
  },
  {
    "Episode Number Overall": 47,
    "Season Number": 3,
    "Episode": 19,
    "Title": "The Negotiation",
    "Hint":"Bippity Boppity give me the Zoppity",
  },
  {
    "Episode Number Overall": 48,
    "Season Number": 3,
    "Episode": 20,
    "Title": "Safety Training",
    "Hint":"Dwight you ignorant slut",
  },
  {
    "Episode Number Overall": 49,
    "Season Number": 3,
    "Episode": 21,
    "Title": "Product Recall",
    "Hint":"Creed gets Debbie Brown fired",
  },
  {
    "Episode Number Overall": 50,
    "Season Number": 3,
    "Episode": 22,
    "Title": "Women’s Appreciation",
    "Hint":"Michael would love to buy Angela a fresh set of underwear",
  },
  {
    "Episode Number Overall": 51,
    "Season Number": 3,
    "Episode": 23,
    "Title": "Beach Games",
    "Hint":"Where is Andy? Andy is... never here today",
  },
  {
    "Episode Number Overall": 52,
    "Season Number": 3,
    "Episode": 24,
    "Title": "The Job",
    "Hint":"No Karen, you're kind of a bitch.",
  },
  {
    "Episode Number Overall": 53,
    "Season Number": 3,
    "Episode": 25,
    "Title": "The Job Part 2",
    "Hint":"IT'S A DATE!",
  },
  {
    "Episode Number Overall": 54,
    "Season Number": 4,
    "Episode": 1,
    "Title": "Fun Run",
    "Hint":"Michael mows down Meredith",
  },
  {
    "Episode Number Overall": 55,
    "Season Number": 4,
    "Episode": 2,
    "Title": "Fun Run Part 2",
    "Hint":"The fettucini is sitting in my stomach like a rock.",
  },
  {
    "Episode Number Overall": 56,
    "Season Number": 4,
    "Episode": 3,
    "Title": "Dunder Mifflin Infinity",
    "Hint":"I have a lot of questions. First off: How dare you?",
  },
  {
    "Episode Number Overall": 57,
    "Season Number": 4,
    "Episode": 4,
    "Title": "Dunder Mifflin Infinity Part 2",
    "Hint":"You deal with this or you, me, Sammy, Phyllis, the chick you hit with the car, we’re goners.",
  },
  {
    "Episode Number Overall": 58,
    "Season Number": 4,
    "Episode": 5,
    "Title": "Launch Party",
    "Hint":"Dwight seeks to outsell the website",
  },
  {
    "Episode Number Overall": 59,
    "Season Number": 4,
    "Episode": 6,
    "Title": "Launch Party Part 2",
    "Hint":"Michael kidnaps a pizza delivery boy.",
  },
  {
    "Episode Number Overall": 60,
    "Season Number": 4,
    "Episode": 7,
    "Title": "Money",
    "Hint":"Jim and Pam stay at Schrute Farms",
  },
  {
    "Episode Number Overall": 61,
    "Season Number": 4,
    "Episode": 8,
    "Title": "Money Part 2",
    "Hint":"Michael hops a train",
  },
  {
    "Episode Number Overall": 62,
    "Season Number": 4,
    "Episode": 9,
    "Title": "Local Ad",
    "Hint":"Pam tries her hand at animation for part of Michael's project.",
  },
  {
    "Episode Number Overall": 63,
    "Season Number": 4,
    "Episode": 10,
    "Title": "Branch Wars",
    "Hint":"Nothing with the eyes, Dwight!",
  },
  {
    "Episode Number Overall": 64,
    "Season Number": 4,
    "Episode": 11,
    "Title": "Survivor Man",
    "Hint":"I! HAVE! HEMMORHOIDS!",
  },
  {
    "Episode Number Overall": 65,
    "Season Number": 4,
    "Episode": 12,
    "Title": "The Deposition",
    "Hint":"My friend Pat took a turn. My friend Disré got new specs.",
  },
  {
    "Episode Number Overall": 66,
    "Season Number": 4,
    "Episode": 13,
    "Title": "Dinner Party",
    "Hint":"You know I have soft teeth how could you say that?",
  },
  {
    "Episode Number Overall": 67,
    "Season Number": 4,
    "Episode": 14,
    "Title": "Chair Model",
    "Hint":"We had lots of kids... Drinkin' whiskey and rye...",
  },
  {
    "Episode Number Overall": 68,
    "Season Number": 4,
    "Episode": 15,
    "Title": "Night Out",
    "Hint":"You resemble a Tolkein character. No not a wizard, a hobbit.",
  },
  {
    "Episode Number Overall": 69,
    "Season Number": 4,
    "Episode": 16,
    "Title": "Did I Stutter?",
    "Hint":"Stanley, this was a fake firing",
  },
  {
    "Episode Number Overall": 70,
    "Season Number": 4,
    "Episode": 17,
    "Title": "Job Fair",
    "Hint":"PAM PAM PAM and then you sneezed in my tea",
  },
  {
    "Episode Number Overall": 71,
    "Season Number": 4,
    "Episode": 18,
    "Title": "Goodbye, Toby",
    "Hint":"Holly-llujah! It's Mike-raculous",
  },
  {
    "Episode Number Overall": 72,
    "Season Number": 4,
    "Episode": 19,
    "Title": "Goodbye, Toby Part 2",
    "Hint":"Phyllis catches Dwight and Angela",
  },
  {
    "Episode Number Overall": 73,
    "Season Number": 5,
    "Episode": 1,
    "Title": "Weight Loss",
    "Hint":"Pam, you weigh 226 pounds?",
  },
  {
    "Episode Number Overall": 74,
    "Season Number": 5,
    "Episode": 2,
    "Title": "Weight Loss Part 2",
    "Hint":"The rest stop where that soda exploded on me. Exit 17, I think. 1 o’clock.",
  },
  {
    "Episode Number Overall": 75,
    "Season Number": 5,
    "Episode": 3,
    "Title": "Business Ethics",
    "Hint":"Why the steak coupons? If she was already getting the discount?",
  },
  {
    "Episode Number Overall": 76,
    "Season Number": 5,
    "Episode": 4,
    "Title": "Baby Shower",
    "Hint":"The pink M&Ms with Astird on them.",
  },
  {
    "Episode Number Overall": 77,
    "Season Number": 5,
    "Episode": 5,
    "Title": "Crime Aid",
    "Hint":"Those Springsteen tickets seemed really too good to be true",
  },
  {
    "Episode Number Overall": 78,
    "Season Number": 5,
    "Episode": 6,
    "Title": "Employee Transfer",
    "Hint":"Life is a highway, and I wanna ride it all the way back to Nashua.",
  },
  {
    "Episode Number Overall": 79,
    "Season Number": 5,
    "Episode": 7,
    "Title": "Customer Survey",
    "Hint":"BUTTLICKER! OUR PRICES HAVE NEVER BEEN LOWER",
  },
  {
    "Episode Number Overall": 80,
    "Season Number": 5,
    "Episode": 8,
    "Title": "Business Trip",
    "Hint":"You look, how you say, radiant tonight.",
  },
  {
    "Episode Number Overall": 81,
    "Season Number": 5,
    "Episode": 9,
    "Title": "Frame Toby",
    "Hint":"NOOOO! GOD! No, God, please no! No! No! NOOO! ",
  },
  {
    "Episode Number Overall": 82,
    "Season Number": 5,
    "Episode": 10,
    "Title": "The Surplus",
    "Hint":"Explain it to me like I'm five",
  },
  {
    "Episode Number Overall": 83,
    "Season Number": 5,
    "Episode": 11,
    "Title": "Moroccan Christmas",
    "Hint":"Not the best time for an intervention...",
  },
  {
    "Episode Number Overall": 84,
    "Season Number": 5,
    "Episode": 12,
    "Title": "The Duel",
    "Hint":"The Prius is silent if he keeps it under 5mph. He deserves the win.",
  },
  {
    "Episode Number Overall": 85,
    "Season Number": 5,
    "Episode": 13,
    "Title": "Prince Family Paper",
    "Hint":"More like the sucker family!",
  },
  {
    "Episode Number Overall": 86,
    "Season Number": 5,
    "Episode": 14,
    "Title": "Stress Relief",
    "Hint":"Did you have to cut the face off the dummy?",
  },
  {
    "Episode Number Overall": 87,
    "Season Number": 5,
    "Episode": 15,
    "Title": "Stress Relief Part 2",
    "Hint":"Stanley you crush your wife during sex and your heart sucks. Boom roasted!",
  },
  {
    "Episode Number Overall": 88,
    "Season Number": 5,
    "Episode": 16,
    "Title": "Lecture Circuit: Part 1",
    "Hint":"Would a liar bring mini Mounds bars?",
  },
  {
    "Episode Number Overall": 89,
    "Season Number": 5,
    "Episode": 17,
    "Title": "Lecture Circuit: Part 2",
    "Hint":"Michael steals the sleeve of her sweater",
  },
  {
    "Episode Number Overall": 90,
    "Season Number": 5,
    "Episode": 18,
    "Title": "Blood Drive",
    "Hint":"I don't think I ate for three days. *faints*",
  },
  {
    "Episode Number Overall": 91,
    "Season Number": 5,
    "Episode": 19,
    "Title": "Golden Ticket",
    "Hint":"Good morning Mr. Wonka here are your messages",
  },
  {
    "Episode Number Overall": 92,
    "Season Number": 5,
    "Episode": 20,
    "Title": "New Boss",
    "Hint":"You have no idea how high I can fly",
  },
  {
    "Episode Number Overall": 93,
    "Season Number": 5,
    "Episode": 21,
    "Title": "Two Weeks",
    "Hint":"Any good headhunter knows that I am available",
  },
  {
    "Episode Number Overall": 94,
    "Season Number": 5,
    "Episode": 22,
    "Title": "Dream Team",
    "Hint":"Michael, Pam, Ryan, Vikram",
  },
  {
    "Episode Number Overall": 95,
    "Season Number": 5,
    "Episode": 23,
    "Title": "Michael Scott Paper Company",
    "Hint":"Cheese Balls",
  },
  {
    "Episode Number Overall": 96,
    "Season Number": 5,
    "Episode": 24,
    "Title": "Heavy Competition",
    "Hint":"Their meatball parm is their WORST SANDWICH.",
  },
  {
    "Episode Number Overall": 97,
    "Season Number": 5,
    "Episode": 25,
    "Title": "Broke",
    "Hint":"Well well well, how the turntables...",
  },
  {
    "Episode Number Overall": 98,
    "Season Number": 5,
    "Episode": 26,
    "Title": "Casual Friday",
    "Hint":"Meredith your boob is out.",
  },
  {
    "Episode Number Overall": 99,
    "Season Number": 5,
    "Episode": 27,
    "Title": "Cafe Disco",
    "Hint":"I hear it too, boss",
  },
  {
    "Episode Number Overall": 100,
    "Season Number": 5,
    "Episode": 28,
    "Title": "Company Picnic",
    "Hint":"SlumDUNDER MIFFLINaire",
  },
  {
    "Episode Number Overall": 101,
    "Season Number": 6,
    "Episode": 1,
    "Title": "Gossip",
    "Hint":"Stanley's having an affair?",
  },
  {
    "Episode Number Overall": 102,
    "Season Number": 6,
    "Episode": 2,
    "Title": "The Meeting",
    "Hint":" I should have known that he can do just as much damage in the dark.",
  },
  {
    "Episode Number Overall": 103,
    "Season Number": 6,
    "Episode": 3,
    "Title": "The Promotion",
    "Hint":"WHAT DOES A BEAN MEAN",
  },
  {
    "Episode Number Overall": 104,
    "Season Number": 6,
    "Episode": 4,
    "Title": "Niagara",
    "Hint":"We should have hired a professional to take our mental pictures.",
  },
  {
    "Episode Number Overall": 105,
    "Season Number": 6,
    "Episode": 5,
    "Title": "Niagara Part 2",
    "Hint":"You! And me! Moving at the speed of light, into eternity!",
  },
  {
    "Episode Number Overall": 106,
    "Season Number": 6,
    "Episode": 6,
    "Title": "Mafia",
    "Hint":"I'll have the gabbagool",
  },
  {
    "Episode Number Overall": 107,
    "Season Number": 6,
    "Episode": 7,
    "Title": "The Lover",
    "Hint":"A green Toyota Camry, and the seats go alllll the way back",
  },
  {
    "Episode Number Overall": 108,
    "Season Number": 6,
    "Episode": 8,
    "Title": "Koi Pond",
    "Hint":"That's enough carping",
  },
  {
    "Episode Number Overall": 109,
    "Season Number": 6,
    "Episode": 9,
    "Title": "Double Date",
    "Hint":"Helene's worst 49th birthday yet",
  },
  {
    "Episode Number Overall": 110,
    "Season Number": 6,
    "Episode": 10,
    "Title": "Murder",
    "Hint":"My name is Caleb Crawdad I do declare",
  },
  {
    "Episode Number Overall": 111,
    "Season Number": 6,
    "Episode": 11,
    "Title": "Shareholder Meeting",
    "Hint":"I might do the spin",
  },
  {
    "Episode Number Overall": 112,
    "Season Number": 6,
    "Episode": 12,
    "Title": "Scott’s Tots",
    "Hint":"Whatcha gonna do? Make our dreams come true!",
  },
  {
    "Episode Number Overall": 113,
    "Season Number": 6,
    "Episode": 13,
    "Title": "Secret Santa",
    "Hint":"Sit on my lap and there will be no doubt!",
  },
  {
    "Episode Number Overall": 114,
    "Season Number": 6,
    "Episode": 14,
    "Title": "The Banker",
    "Hint":"Obligatory clip show episode",
  },
  {
    "Episode Number Overall": 115,
    "Season Number": 6,
    "Episode": 15,
    "Title": "Sabre",
    "Hint":"Our first appearance of Gabriel Susan Lewis",
  },
  {
    "Episode Number Overall": 116,
    "Season Number": 6,
    "Episode": 16,
    "Title": "The Manager and the Salesman",
    "Hint":"Two guys doing one job? We gotta do something about that!",
  },
  {
    "Episode Number Overall": 117,
    "Season Number": 6,
    "Episode": 17,
    "Title": "The Delivery",
    "Hint":"You want to eat catfood with Kevin and not go to the hospital?",
  },
  {
    "Episode Number Overall": 118,
    "Season Number": 6,
    "Episode": 18,
    "Title": "The Delivery Part 2",
    "Hint":"That baby is going to have a lot of hair",
  },
  {
    "Episode Number Overall": 119,
    "Season Number": 6,
    "Episode": 19,
    "Title": "St. Patrick’s Day",
    "Hint":"The closest that the Irish will ever get to Christmas",
  },
  {
    "Episode Number Overall": 120,
    "Season Number": 6,
    "Episode": 20,
    "Title": "New Leads",
    "Hint":"Hope grows... In a dump.",
  },
  {
    "Episode Number Overall": 121,
    "Season Number": 6,
    "Episode": 21,
    "Title": "Happy Hour",
    "Hint":"Hi I'm Date Mike. Nice to meet me.",
  },
  {
    "Episode Number Overall": 122,
    "Season Number": 6,
    "Episode": 22,
    "Title": "Secretary’s Day",
    "Hint":"Did you have a favorite age? Or month? ",
  },
  {
    "Episode Number Overall": 123,
    "Season Number": 6,
    "Episode": 23,
    "Title": "Body Language",
    "Hint":"Most printer sales are done over the phone, Ms. Boob Shirt",
  },
  {
    "Episode Number Overall": 124,
    "Season Number": 6,
    "Episode": 24,
    "Title": "The Cover-Up",
    "Hint":"If you’re watching this, it’s because I’ve turned State’s witness because I’m in danger because I know too much. ",
  },
  {
    "Episode Number Overall": 125,
    "Season Number": 6,
    "Episode": 25,
    "Title": "The Chump",
    "Hint":"It was either living with myself or... being happy. And I picked... the... former. ",
  },
  {
    "Episode Number Overall": 126,
    "Season Number": 6,
    "Episode": 26,
    "Title": "Whistleblower",
    "Hint":"Going through a bit of a rough patch. The whole year actually.",
  },
  {
    "Episode Number Overall": 127,
    "Season Number": 7,
    "Episode": 1,
    "Title": "Nepotism",
    "Hint":"YOU WILL LEARN TO BE MORE PROFESSIONAL LUKE",
  },
  {
    "Episode Number Overall": 128,
    "Season Number": 7,
    "Episode": 2,
    "Title": "Counseling",
    "Hint":"Toby almost has a breakthrough with Michael",
  },
  {
    "Episode Number Overall": 129,
    "Season Number": 7,
    "Episode": 3,
    "Title": "Andy’s Play",
    "Hint":"ATTEND THE TALE OF SWEENEY TODD",
  },
  {
    "Episode Number Overall": 130,
    "Season Number": 7,
    "Episode": 4,
    "Title": "Sex Ed",
    "Hint":"I can't even say it. H. I. R. P. E. E. S.",
  },
  {
    "Episode Number Overall": 131,
    "Season Number": 7,
    "Episode": 5,
    "Title": "The Sting",
    "Hint":"Danny Cordray is a heartthrob",
  },
  {
    "Episode Number Overall": 132,
    "Season Number": 7,
    "Episode": 6,
    "Title": "Costume Contest",
    "Hint":"Shake things up; I'm a Nader guy.",
  },
  {
    "Episode Number Overall": 133,
    "Season Number": 7,
    "Episode": 7,
    "Title": "Christening",
    "Hint":"Sconesy Cider : Famed baptism reception critic",
  },
  {
    "Episode Number Overall": 134,
    "Season Number": 7,
    "Episode": 8,
    "Title": "Viewing Party",
    "Hint":"Ya know who my favorite character is? The invalid.",
  },
  {
    "Episode Number Overall": 135,
    "Season Number": 7,
    "Episode": 9,
    "Title": "WUPHF.com",
    "Hint":"Washington University Public Health Fund.",
  },
  {
    "Episode Number Overall": 136,
    "Season Number": 7,
    "Episode": 10,
    "Title": "China",
    "Hint":"There are 56 cities with over a million people",
  },
  {
    "Episode Number Overall": 137,
    "Season Number": 7,
    "Episode": 11,
    "Title": "Classy Christmas",
    "Hint":"Isn't that just so magical for you, little girl?",
  },
  {
    "Episode Number Overall": 138,
    "Season Number": 7,
    "Episode": 12,
    "Title": "Classy Christmas Part 2",
    "Hint":"Open Immediately : Love, Swiss Cheese",
  },
  {
    "Episode Number Overall": 139,
    "Season Number": 7,
    "Episode": 13,
    "Title": "Ultimatum",
    "Hint":"I did it! The perfect cartwheel!",
  },
  {
    "Episode Number Overall": 140,
    "Season Number": 7,
    "Episode": 14,
    "Title": "The Seminar",
    "Hint":"My name is Mykonos",
  },
  {
    "Episode Number Overall": 141,
    "Season Number": 7,
    "Episode": 15,
    "Title": "The Search",
    "Hint":"You don't think he walked by that bakery, just for the smell of it?",
  },
  {
    "Episode Number Overall": 142,
    "Season Number": 7,
    "Episode": 16,
    "Title": "PDA",
    "Hint":"Suck it, Oscar, this must kill you!",
  },
  {
    "Episode Number Overall": 143,
    "Season Number": 7,
    "Episode": 17,
    "Title": "Threat Level Midnight",
    "Hint":"There's gonna be a cleanup on Aisle 5",
  },
  {
    "Episode Number Overall": 144,
    "Season Number": 7,
    "Episode": 18,
    "Title": "Todd Packer",
    "Hint":"My daughter's turning into a real bitch.",
  },
  {
    "Episode Number Overall": 145,
    "Season Number": 7,
    "Episode": 19,
    "Title": "Garage Sale",
    "Hint":"Holly Flax- Marrying me will you be?",
  },
  {
    "Episode Number Overall": 146,
    "Season Number": 7,
    "Episode": 20,
    "Title": "Training Day",
    "Hint":"Nice to meet you, D'Angelo Vickers",
  },
  {
    "Episode Number Overall": 147,
    "Season Number": 7,
    "Episode": 21,
    "Title": "Michael’s Last Dundies",
    "Hint":"I have Vienna Sausages, and... napkins... Let me fix you breakfast!",
  },
  {
    "Episode Number Overall": 148,
    "Season Number": 7,
    "Episode": 22,
    "Title": "Goodbye, Michael",
    "Hint":"9,986,000 minutes! That's like watching Die Hard, 80,000 times.",
  },
  {
    "Episode Number Overall": 149,
    "Season Number": 7,
    "Episode": 23,
    "Title": "The Inner Circle",
    "Hint":"I can do Jordan's dunk, from the freethrow line.",
  },
  {
    "Episode Number Overall": 150,
    "Season Number": 7,
    "Episode": 24,
    "Title": "Dwight K. Schrute, (Acting) Manager",
    "Hint":"IT WAS A BEAUMONT ADAMS",
  },
  {
    "Episode Number Overall": 151,
    "Season Number": 7,
    "Episode": 25,
    "Title": "Search Committee",
    "Hint":"Corporate needs you to find the difference between these photos",
  },
  {
    "Episode Number Overall": 152,
    "Season Number": 7,
    "Episode": 26,
    "Title": "Search Committee Part 2",
    "Hint":"Give Dwight an interivew. I like a little bit of crazy.",
  },
  {
    "Episode Number Overall": 153,
    "Season Number": 8,
    "Episode": 1,
    "Title": "The List",
    "Hint":"Winners and losers",
  },
  {
    "Episode Number Overall": 154,
    "Season Number": 8,
    "Episode": 2,
    "Title": "The Incentive",
    "Hint":"Classic ass tattoo",
  },
  {
    "Episode Number Overall": 155,
    "Season Number": 8,
    "Episode": 3,
    "Title": "Lotto",
    "Hint":"I don't technically have a hearing problem...",
  },
  {
    "Episode Number Overall": 156,
    "Season Number": 8,
    "Episode": 4,
    "Title": "Garden Party",
    "Hint":"JAMES, PAMELA, AND PEEPEE HALPERT",
  },
  {
    "Episode Number Overall": 157,
    "Season Number": 8,
    "Episode": 5,
    "Title": "Spooked",
    "Hint":"KERRIGAN IS LEADER OF THE ZERG SWARM",
  },
  {
    "Episode Number Overall": 158,
    "Season Number": 8,
    "Episode": 6,
    "Title": "Doomsday",
    "Hint":"If you find another horse, you've dug too far.",
  },
  {
    "Episode Number Overall": 159,
    "Season Number": 8,
    "Episode": 7,
    "Title": "Pam’s Replacement",
    "Hint":"Dwight gets a real handful",
  },
  {
    "Episode Number Overall": 160,
    "Season Number": 8,
    "Episode": 8,
    "Title": "Gettysburg",
    "Hint":"Schrute Farms you say? That is a fascinating little chapter of the Civil War.",
  },
  {
    "Episode Number Overall": 161,
    "Season Number": 8,
    "Episode": 9,
    "Title": "Mrs. California",
    "Hint":"Andy misinterprets cryptic messages and hires the CEO's wife",
  },
  {
    "Episode Number Overall": 162,
    "Season Number": 8,
    "Episode": 10,
    "Title": "Christmas Wishes",
    "Hint":"Andy is Meredith's DD",
  },
  {
    "Episode Number Overall": 163,
    "Season Number": 8,
    "Episode": 11,
    "Title": "Trivia",
    "Hint":"A gay bar in Philadelphia",
  },
  {
    "Episode Number Overall": 164,
    "Season Number": 8,
    "Episode": 12,
    "Title": "Pool Party",
    "Hint":"On Golden Fucking Pond",
  },
  {
    "Episode Number Overall": 165,
    "Season Number": 8,
    "Episode": 13,
    "Title": "Jury Duty",
    "Hint":"Jim buys everyone Ernesto's for lunch",
  },
  {
    "Episode Number Overall": 166,
    "Season Number": 8,
    "Episode": 14,
    "Title": "Special Project",
    "Hint":"Dwight gets an opportunity for a business trip.",
  },
  {
    "Episode Number Overall": 167,
    "Season Number": 8,
    "Episode": 15,
    "Title": "Tallahassee",
    "Hint":"Stanley loves him some rum",
  },
  {
    "Episode Number Overall": 168,
    "Season Number": 8,
    "Episode": 16,
    "Title": "After Hours",
    "Hint":"I hope y'all like goat",
  },
  {
    "Episode Number Overall": 169,
    "Season Number": 8,
    "Episode": 17,
    "Title": "Test the Store",
    "Hint":"Unleash the power of the Pyramid",
  },
  {
    "Episode Number Overall": 170,
    "Season Number": 8,
    "Episode": 18,
    "Title": "Last Day in Florida",
    "Hint":"Let Dwight have his fun. Today will not be his day.",
  },
  {
    "Episode Number Overall": 171,
    "Season Number": 8,
    "Episode": 19,
    "Title": "Get the Girl",
    "Hint":"Signed, sealed, delivered, I'm yours!",
  },
  {
    "Episode Number Overall": 172,
    "Season Number": 8,
    "Episode": 20,
    "Title": "Welcome Party",
    "Hint":"Nellie finds an empty seat.",
  },
  {
    "Episode Number Overall": 173,
    "Season Number": 8,
    "Episode": 21,
    "Title": "Angry Andy",
    "Hint":"Andy punches the wall again?",
  },
  {
    "Episode Number Overall": 174,
    "Season Number": 8,
    "Episode": 22,
    "Title": "Fundraiser",
    "Hint":"Andy's been working too hard on his Rock Opera...",
  },
  {
    "Episode Number Overall": 175,
    "Season Number": 8,
    "Episode": 23,
    "Title": "Turf War",
    "Hint":"Harry Jannerone, Syracuse.",
  },
  {
    "Episode Number Overall": 176,
    "Season Number": 9,
    "Episode": 24,
    "Title": "Free Family Portrait Studio",
    "Hint":"Dwight steals a diaper to run some DNA tests",
  },
  {
    "Episode Number Overall": 177,
    "Season Number": 9,
    "Episode": 1,
    "Title": "New Guys",
    "Hint":"Plop and Dwight Junior enter the chat.",
  },
  {
    "Episode Number Overall": 178,
    "Season Number": 9,
    "Episode": 2,
    "Title": "Roy’s Wedding",
    "Hint":"Yeah. I’m afraid he’s only gonna have hot dogs. ",
  },
  {
    "Episode Number Overall": 179,
    "Season Number": 9,
    "Episode": 3,
    "Title": "Andy's Ancestry",
    "Hint":"Pam, I am related to Tonya Harding.",
  },
  {
    "Episode Number Overall": 180,
    "Season Number": 9,
    "Episode": 4,
    "Title": "Work Bus",
    "Hint":"Laverne's Pies, Tires Fixed Also",
  },
  {
    "Episode Number Overall": 181,
    "Season Number": 9,
    "Episode": 5,
    "Title": "Here Comes Treble",
    "Hint":"Pam REALLY hates the Monster Mash.",
  },
  {
    "Episode Number Overall": 182,
    "Season Number": 9,
    "Episode": 6,
    "Title": "The Boat",
    "Hint":"The point was to sail the damn thing.",
  },
  {
    "Episode Number Overall": 183,
    "Season Number": 9,
    "Episode": 7,
    "Title": "The Whale",
    "Hint":"Dwight sells to the Scranton White Pages.",
  },
  {
    "Episode Number Overall": 184,
    "Season Number": 9,
    "Episode": 8,
    "Title": "The Target",
    "Hint":"Angela takes out a hit on Oscar",
  },
  {
    "Episode Number Overall": 185,
    "Season Number": 9,
    "Episode": 9,
    "Title": "Dwight Christmas",
    "Hint":"Impish? Or Admirable?",
  },
  {
    "Episode Number Overall": 186,
    "Season Number": 9,
    "Episode": 10,
    "Title": "Lice",
    "Hint":"Jim shoots hoops with Julius Erving.",
  },
  {
    "Episode Number Overall": 187,
    "Season Number": 9,
    "Episode": 11,
    "Title": "Suit Warehouse",
    "Hint":"Dwight used to eat cat turds?",
  },
  {
    "Episode Number Overall": 188,
    "Season Number": 9,
    "Episode": 12,
    "Title": "Customer Loyalty",
    "Hint":"Darryl is joining Jim's 'Stumpany'",
  },
  {
    "Episode Number Overall": 189,
    "Season Number": 9,
    "Episode": 13,
    "Title": "Junior Salesman",
    "Hint":"Dwight Junior is taking Jim's desk.",
  },
  {
    "Episode Number Overall": 190,
    "Season Number": 9,
    "Episode": 14,
    "Title": "Vandalism",
    "Hint":"Warehouse douche paints a butt",
  },
  {
    "Episode Number Overall": 191,
    "Season Number": 9,
    "Episode": 15,
    "Title": "Couples Discount",
    "Hint":"Darryl and Oscar pose as lovers for some reduced price foot massages.",
  },
  {
    "Episode Number Overall": 192,
    "Season Number": 9,
    "Episode": 16,
    "Title": "Moving On",
    "Hint":"I saw Pete's butt. It's sick.",
  },
  {
    "Episode Number Overall": 193,
    "Season Number": 9,
    "Episode": 17,
    "Title": "The Farm",
    "Hint":"Nostalgia is truly one of the great human weaknesses. Second only to the neck. ",
  },
  {
    "Episode Number Overall": 194,
    "Season Number": 9,
    "Episode": 18,
    "Title": "Promos",
    "Hint":"The Office: An American Workplace. Coming soon on WVIA. ",
  },
  {
    "Episode Number Overall": 195,
    "Season Number": 9,
    "Episode": 19,
    "Title": "Stairmageddon",
    "Hint":"Nothing to be alarmed about. It’s just a man pointing a bull tranquilizer at a coworker.",
  },
  {
    "Episode Number Overall": 196,
    "Season Number": 9,
    "Episode": 20,
    "Title": "Paper Airplane",
    "Hint":"We are now down to an elite eight. Well, seven and Toby. ",
  },
  {
    "Episode Number Overall": 197,
    "Season Number": 9,
    "Episode": 21,
    "Title": "Livin’ the Dream",
    "Hint":"I mean, I was interim manager once, but then I shot that gun. ",
  },
  {
    "Episode Number Overall": 198,
    "Season Number": 9,
    "Episode": 22,
    "Title": "A. A. R. M.",
    "Hint":"The tea in Nepal is very hot. But the coffee in Peru is MUCH hotter.",
  },
  {
    "Episode Number Overall": 199,
    "Season Number": 9,
    "Episode": 23,
    "Title": "A. A. R. M. Part 2",
    "Hint":"THIS EXPRESSES HOW LOUDLY I LOVE YOU.",
  },
  {
    "Episode Number Overall": 200,
    "Season Number": 9,
    "Episode": 24,
    "Title": "Finale",
    "Hint":"PBS. The propaganda wing of Bill and Melinda Gates and viewers like you. ",
  },
  {
    "Episode Number Overall": 201,
    "Season Number": 9,
    "Episode": 25,
    "Title": "Finale Part 2",
    "Hint":"There’s a lot of beauty in ordinary things. Isn’t that kind of the point? ",
  },
]


export default answers

const count=answers.length

// export const getRandomAnswer = () => {
//     return answers[14]
// }
export const getRandomAnswer = () => {
    const idx= Math.floor(Math.random() * count);
    return answers[idx]
}
